version: '3.9'

name: realtime-chat-upstash
services:
  chat-app-1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - CORS_ORIGIN=${CORS_ORIGIN}
      - UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL}

  chat-app-2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - CORS_ORIGIN=${CORS_ORIGIN}
      - UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL}
  
  chat-app-3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - CORS_ORIGIN=${CORS_ORIGIN}
      - UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL}

  caddy:
    image: caddy/caddy:2.7.3-alpine
    container_name: caddy-server
    restart: unless-stopped
    ports:
      - "82:80"
      - "4432:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: